apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rocketmq-operator
  template:
    metadata:
      labels:
        name: rocketmq-operator
    spec:
      serviceAccountName: rocketmq-operator
      containers:
        - name: rocketmq-operator
          # Replace this with the built image name
          image: 2019liurui/rocketmq-operator:v0.0.1-snapshot
          command:
          - rocketmq-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "rocketmq-operator"
